### ISSUE TITLE
Serialization of case classes with hierarchy gives : ambiguous implicit values

### ISSUE THREAD

**Issue by jarekratajski** [lihaoyi/upickle#118]
I have created small project where I isolated project and described quite strange behaviour:
https://github.com/jarekratajski/upickleproblem

dev/upikle2/src/main/scala/sample/CR.scala:10: ambiguous implicit values:
[error]  both value derive$macro$12 of type => upickle.default.Writer[sample.CR]
[error]  and value derive$macro$13 of type => upickle.default.Writer[sample.PI]
[error]  match expected type upickle.default.Writer[T1]
[error]     writeJs(this)
[error]            ^
[error] one error found
[error](compile:compileIncremental) Compilation failed

We have project with lot of case classes and this issue is really causing problems (we move class or change small field and compilation fails).

**Comment by Voltir** [comment]
So, thats an interesting consequence of having def toJSValue(): upickle.Js.Value functions inside of the same case classes being targets for upickling. 

Basically, what ends up happening is that the implicit Writer definition for classes like CR end up being generated twice, which actually is ambiguous. The solution to this problem is to prevent the macro from trying to generate an implicit for you the second time, ie do this:

```scala
  def toJSValue()(implicit writer: upickle.default.Writer[CR]): upickle.Js.Value = {
    writer.write(this)
  }
```

**Comment by lihaoyi** [comment]
Another example, in the Ammonite console
```scala
@ upickle.json.read("")
Compilation Failed
ambiguous implicit values:
 both value derive$macro$125 of type => pprint.PPrint[upickle.Js.Value]
 and value derive$macro$127 of type => pprint.PPrint[upickle.Js.Value]
 match expected type pprint.PPrint[upickle.Js.Value]
ambiguous implicit values:
 both value derive$macro$125 of type => pprint.PPrint[upickle.Js.Value]
 and value derive$macro$127 of type => pprint.PPrint[upickle.Js.Value]
 match expected type pprint.PPrint[upickle.Js.Value]
```

**Comment by lihaoyi** [comment]
Bug bankruptcy
