### ISSUE TITLE
java.util.UUID reader and writer cannot be implemented due to assertion

### ISSUE THREAD

**Issue by krm2** [lihaoyi/upickle#67]
I'm attempting to create implicit converters for the UUID class, as such:

    object Helper {
      implicit val uuid2Writer = upickle.Writer[UUID] {
        case t: UUID => Js.Str(t.toString)
      }
      implicit val uuid2Reader = upickle.Reader[UUID] {
        case Js.Str(s) => UUID.fromString(s)
      }
    }

It appears to compile up to the point where it fails an assertion, specifically [Macros.scala:49](https://github.com/lihaoyi/upickle/blob/master/upickle/shared/src/main/scala/upickle/Macros.scala#L49)

    assert(!tpe.typeSymbol.fullName.startsWith("scala."))

As this is a java.util class, it fails the assertion, but what is the purpose of having this here? If this assertion were removed, would my implementation work as intended?

**Comment by tindzk** [comment]
Are you sure this assertion fails because of your implicits as it specifically checks for ``scala.`` and not ``java.``? The problem may be that you did not import the implicits with ``import Helper._`` and uPickle tries to encode UUID's internal structure, which most likely contains ``java.`` types.

You could remove it, although I would advise against it. When refactoring the code, I came across this assertion a few times. The reason why the assertion exists is that uPickle implements all native types in ``Implicits`` and the macros should be only executed for user-defined types.

Your two implicits look reasonable and I don't see any reason why they should not be part of uPickle itself. So you could add them directly to the ``Implicits`` trait.

**Comment by krm2** [comment]
You are correct. Importing `Helper` appears to work.

That said, is it actually possible to extend the existing `Implicits` trait without modifying upickle itself?

**Comment by tindzk** [comment]
No, right now this is not possible, which is one of the reasons why it would make sense to structure uPickle using the Cake approach internally (see #59).

Let's wait for Li to comment on this issue. I guess he wouldn't mind if your implicits become part of the upstream code.

**Comment by lihaoyi** [comment]
Haven't had time to look at it, but in principle it seems reasonable now
that java.util.UUID works in Scala.js out of the box
